### ISSUE TITLE
it no work

### ISSUE THREAD

**Issue by adamtowerz** [IndianBoy42/cah-rs#1]
much excite, such cry

> src/main.rs:1:1: 1:18 error: #[feature] may not be used on the stable release channel
> src/main.rs:1 #![feature(core)]
>              ^~~~~~~~~~~~~~~~~
> error: aborting due to previous error
> Could not compile `CAH`.

idk if this is build ready or not, but yeaaa

**Comment by IndianBoy42** [comment]
oh right lol
i havent looked at this project in a while

youre gonna have to use the beta or nightly builds of rust to even compile
after that im not sure

**Comment by IndianBoy42** [comment]
ill probably work on it in the holidays if i have time and interest

**Comment by adamtowerz** [comment]
oh ok lol
